name: my first workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
